<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GawishERP.Domain\GawishERP.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Features\Identity\" />
    <Folder Include="Features\Companies\" />
    <Folder Include="Features\Branches\" />
    <Folder Include="Features\Permissions\" />
    <Folder Include="Features\Roles\" />
    <Folder Include="Features\Users\" />
    <Folder Include="Interfaces\" />
    <Folder Include="DTOs\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
