<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\GawishERP.Domain\GawishERP.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Common\Base\" />
		<Folder Include="Common\CRUD\" />
		<Folder Include="Common\Validation\" />
		<Folder Include="Features\Accounting\AccountStatement\Validators\" />
		<Folder Include="Features\Accounting\GeneralLedger\Validators\" />
		<Folder Include="Features\Accounting\JournalEntries\Commands\Delete\" />
		<Folder Include="Features\Accounting\JournalEntries\Commands\Update\" />
		<Folder Include="Features\Accounting\JournalEntries\Mapping\" />
		<Folder Include="Features\Accounting\JournalEntries\Validators\" />
		<Folder Include="Features\Accounting\OpeningBalances\Validators\" />
		<Folder Include="Features\Dashboard\DTOs\" />
		<Folder Include="Features\Dashboard\Queries\" />
		<Folder Include="Features\FiscalYears\Validators\" />
		<Folder Include="Features\PeriodClosing\Commands\" />
		<Folder Include="Features\PeriodClosing\DTOs\" />
		<Folder Include="Features\Purchasing\Purchase\Commands\Delete\" />
		<Folder Include="Features\Purchasing\Purchase\Commands\Update\" />
		<Folder Include="Features\Suppliers\Validators\" />
		<Folder Include="Interfaces\" />
		<Folder Include="Services\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="MediatR" Version="14.2.0" />
		<PackageReference Include="AutoMapper" Version="16.2.0" />
	</ItemGroup>

</Project>